name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    # Reads variables from the 'production' Environment (set this up in repo Settings → Environments)
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Disable cache to avoid the Rollup optional-deps bug on CI
          cache: 'none'

      # Clean install to work around npm+rollup optional deps issue on Linux runners
      - name: Clean install (workaround for Rollup optional deps)
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit

      - name: Create .env from GitHub Environment variables
        run: |
          echo "VITE_BASE_URL=${{ vars.VITE_BASE_URL }}" >> .env

      - name: Build
        run: npm run build

      # SPA fallback so client-side routes work on Pages
      - name: Add 404 fallback
        run: |
          cp dist/index.html dist/404.html || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
